### PR TITLE
ArchCNL-50: Fix Managers for Concepts and Relations

### PR DESCRIPTION
**Pull request by VincentRaudszus**
- The input model of the UI is now available from the RuleConceptsAndRelations singleton. It holds the three managers from which the architecture rules, concepts, and relations can be accessed and managed.
- Concept and Relation are now abstract and have a number of subclasses for different uses (like SpecialRelation for regex, TypeRelation for the rdf:type relation, DefaultRelation for famix relations, and CustomRelation for relations with mappings). This implementation results in simplified logic and allows a less hacky implementation of SpecialRelations like regex.
- The ConceptManager and the RelationManager have received unit tests that cover all possible branches.

Additionally, this PR contains other changes and refactorings to the input model:
- ArchRulesToAdocWriter and ArchRulesFromAdocReader have received a refactoring (was necessary as the old implementation was not compatible with the main changes from this PR).
- The introduction of ObjectType heavily simplified the usage of Triplet and also allows for improved type checking.
- The introduction of StringValue and BooleanValue replaces the previous faulty and hacky implementation of such object types.

### CODE REVIEW

**Comment by cmkehler** [comment]
Merge conflicts appeared after previous merges. Could you fix them before I review the code (Or is that part of the reviewers job)?

**Comment by VincentRaudszus** [comment]
I guess that is my job.  My branch is now rebased on the master and thus merge conflicts no longer exist.

**Review by cmkehler — COMMENTED** [review]
Ok looks good. Alex said that streams are preferrable to for loops, but that the for-each loops that you used are still acceptable. In any case generally I would have used for-each loops aswell.
The only question that I have is in Relation.java (Line 32), you catch a InvalidVariableNameException e and then throw a RuntimeException with the message from e. 
Could you explain your reasoning behind doing this? Could InvalidVariableNameException not inherit from RuntimeException in the first place?

**Comment by VincentRaudszus** [comment]
I will take that another look at my for-loops and if possible switch them for Streams.
I use the RuntimeException there to signal that a critical error occurred. RuntimeExceptions are un-checked so throwing them should crash the program (which is what I want as they should never occur where I used them). InvalidVariableNameException is a checked Exception for internal use. It is allowed to occur in the normal program flow but has to be handled which is made sure by it being a checked exception. So it cannot inherit from RuntimeException.

**Pull request merged**
